CREATE TABLE roles (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(255) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 role VARCHAR(50) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE login_attempts (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT NOT NULL,
 timestamp TIMESTAMP NOT NULL,
 ip_address VARCHAR(45) NOT NULL,
 action VARCHAR(50) NOT NULL,
 successful BOOLEAN NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id)
);